services:
  backend01:
    build: ./backend
    environment:
      - SERVER_ID=backend01
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health', timeout=2)"]
      interval: 2s
      timeout: 2s
      retries: 5
      start_period: 3s
    networks: [app_net]

  backend02:
    build: ./backend
    environment:
      - SERVER_ID=backend02
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health', timeout=2)"]
      interval: 2s
      timeout: 2s
      retries: 5
      start_period: 3s
    networks: [app_net]

  backend03:
    build: ./backend
    environment:
      - SERVER_ID=backend03
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health', timeout=2)"]
      interval: 2s
      timeout: 2s
      retries: 5
      start_period: 3s
    networks: [app_net]

  balancer:
    container_name: haproxy
    image: haproxy:2.9
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - "8080:80"
      - "8404:8404"   # painel de stats do HAProxy
    depends_on:
      backend01:
        condition: service_healthy
      backend02:
        condition: service_healthy
      backend03:
        condition: service_healthy
    networks: [app_net]

  k6:
    container_name: k6-haproxy
    image: grafana/k6:latest
    volumes:
      - ./k6:/scripts
      - ../results/haproxy:/results
    environment:
      - BASE_URL=http://balancer:80
      - SCENARIO=baseline # baseline|failure|spike
    user: root
    entrypoint: ["/bin/sh", "-c", "mkdir -p /results && chmod 777 /results && k6 run --out json=/results/$${SCENARIO}.json /scripts/script.js"]
    depends_on:
      - balancer
    networks: [app_net]

networks:
  app_net:
    driver: bridge